name: Shellcheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          additional_files: '*.in'
          ignore_names: >-
            dkms.8.in
            dkms.service.in
            dkms_framework.conf.in
